apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: zipkin-server
  name: zipkin-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: zipkin-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.36.0 (HEAD)
      labels:
        io.kompose.service: zipkin-server
    spec:
      containers:
        - image: openzipkin/zipkin:latest
          name: zipkin-server
          ports:
            - containerPort: 9411
              protocol: TCP
          resources:
            limits:
              memory: "314572800"
      restartPolicy: Always
